version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=database-1.cxsaq0qa4oil.us-east-2.rds.amazonaws.com
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=MI361isfun
      - MYSQL_DATABASE=database-1
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: V!zUG2tag!Rc
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: MI361isfun
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
